services:
  - type: web
    name: stocktraderl
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_CMD
        value: python3
      # NOTE: do NOT hardcode PORT here — Render injects a PORT environment variable at runtime.
      # If you need a database, add DATABASE_URL here or configure via Render dashboard.
      # - key: DATABASE_URL
      #   value: your_database_url_here
