name: Deploy GitHub Pages (Vite client)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Build client for Pages
        env:
          PAGES_BUILD: '1'
          # Set VITE_API_BASE to your deployed backend URL (e.g., Render)
          VITE_API_BASE: ${{ vars.VITE_API_BASE }}
        run: npm run build --silent

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/client/dist
          force_orphan: true


